### ISSUE TITLE
Más ayuda para ejercicio 7

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-paco/mumuki-metaprogramacion-ruby-guia-2#2]
No me acuerdo:
- sintaxis para definir un constructor
- sintaxis de method missing

Tampoco me resulta fácil saber como interceptar un "setter" o asignación al struct.
Suponía que el simbolo del envío del mensaje era algo como "blah=" incluyendo el igual de la asignación, pero parece que no es así.

**Comment by flbulgarelli** [comment]
Fixed
